version: '3.8'

services:
  postgres:
    container_name: postgres-crypto-app
    image: postgres
    environment:
      POSTGRES_PASSWORD: '#CryptoApp2024@'
      POSTGRES_DB: crypto_portfolio
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped